// withAndroidAutoMessaging.js — Expo config plugin that wires the manifest
// entries an Android Auto MESSAGING app needs, so `expo prebuild --clean`
// doesn't wipe them. See docs/yaver-car-voice-coding.md §3 (Tier 1) + §8.
//
// ✅ REGISTERED in app.json (Android-only mods; iOS untouched). This closes the
// Tier-1 gap: the plugin now ALSO injects the native MessagingStyle delivery
// module + reply receiver (see below), so the conversation actually renders and
// is replyable in Android Auto. The JS side stays safe everywhere: with no
// native module compiled in (managed Expo, iOS, tsx tests),
// presentCarConversation() falls back to a best-effort phone notification and
// the Tier 0 loop is unaffected.
//
// VERIFICATION REQUIRED before relying on the head-unit path (the registration
// is build-safe but the head-unit behaviour needs a native run):
//   1. Native rebuild: `expo prebuild --platform android --clean` → restore
//      force-tracked overlays → gradle bundleRelease (~28 min cold). Because
//      every mod here is additive + Android-only, prebuild stays green.
//   2. On-device / emulator verification with the Android Auto Desktop Head
//      Unit (DHU) — NO physical car needed. Steps:
//        a. Install Android Auto + the "Desktop Head Unit" via Android Studio
//           SDK Manager (Android Auto API Simulators).
//        b. On the phone/emulator: Android Auto → Settings → tap the version 10×
//           to unlock Developer settings → enable "Unknown sources" (so the
//           sideloaded Yaver build is allowed) and "Start head unit server".
//        c. `adb forward tcp:5277 tcp:5277` then run `desktop-head-unit` from
//           $ANDROID_HOME/extras/google/auto/.
//        d. Trigger a car conversation (carMessagingNotification.presentCar-
//           Conversation) and confirm the DHU reads the agent message aloud and
//           shows a Reply (voice) action. Speaking a reply should fire the
//           `yaverCarReply` event → carReplyDispatch.handleCarReply.
//
// What this plugin does once registered (Android only — Android Auto):
//   - Adds the <meta-data com.google.android.gms.car.application> entry to the
//     <application>, pointing at @xml/automotive_app_desc.
//   - Writes res/xml/automotive_app_desc.xml declaring the app as a
//     notification-based messaging app (<uses name="notification"/>).
//   - Copies the native MessagingStyle delivery module + reply receiver
//     (mobile/native-androidauto/android/*.kt) into the generated app source
//     set, registers <receiver> YaverCarReplyReceiver in the manifest, and adds
//     YaverCarMessagingPackage() to MainApplication's package list. This is the
//     native consumer of buildAndroidAutoExtras(...) that actually posts an
//     Android-Auto-readable notification (managed expo-notifications can't).
// That pair (meta-data + desc xml) is the entitlement-FREE handshake that makes
// Android Auto treat the app as a messaging source (read-aloud + voice reply);
// the native module is what produces a conversation Auto can read. No
// CarAppService, no androidx.car.app — that heavier IoT/EV surface is a
// separate follow-up.

const {
  withAndroidManifest,
  withDangerousMod,
  withMainApplication,
  AndroidConfig,
} = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const CAR_APP_META_NAME = "com.google.android.gms.car.application";
const CAR_APP_DESC_RESOURCE = "@xml/automotive_app_desc";

// Native Kotlin sources (tracked reference impl) → copied into the generated
// app source set on every prebuild. Package is io.yaver.mobile.car.
const NATIVE_PACKAGE = "io.yaver.mobile.car";
const NATIVE_SOURCES = ["YaverCarMessagingModule.kt", "YaverCarMessagingPackage.kt"];
const REPLY_RECEIVER_NAME = "io.yaver.mobile.car.YaverCarReplyReceiver";

// res/xml/automotive_app_desc.xml — declares a NOTIFICATION (messaging) app.
// Note the absence of any <uses name="media"/> or template entry: that keeps
// us in the entitlement-free messaging lane.
const AUTOMOTIVE_APP_DESC_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by withAndroidAutoMessaging.js. Declares Yaver as a
     notification-based Android Auto messaging app (no entitlement). -->
<automotiveApp>
    <uses name="notification" />
</automotiveApp>
`;

// ---- Android: <meta-data> in <application> --------------------------------
function withCarAppMetaData(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app["meta-data"] = app["meta-data"] || [];
    const exists = app["meta-data"].some(
      (m) => m.$ && m.$["android:name"] === CAR_APP_META_NAME,
    );
    if (!exists) {
      app["meta-data"].push({
        $: {
          "android:name": CAR_APP_META_NAME,
          "android:resource": CAR_APP_DESC_RESOURCE,
        },
      });
    }
    return cfg;
  });
}

// ---- Android: res/xml/automotive_app_desc.xml -----------------------------
function withAutomotiveAppDescResource(config) {
  return withDangerousMod(config, [
    "android",
    (cfg) => {
      const resXmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        "app",
        "src",
        "main",
        "res",
        "xml",
      );
      fs.mkdirSync(resXmlDir, { recursive: true });
      fs.writeFileSync(
        path.join(resXmlDir, "automotive_app_desc.xml"),
        AUTOMOTIVE_APP_DESC_XML,
        "utf8",
      );
      return cfg;
    },
  ]);
}

// ---- Android: copy native Kotlin sources into the app source set ----------
// `expo prebuild --clean` regenerates android/, so we re-copy on every prebuild
// (mirrors withMeshTunnel.js::withMeshIosSources). Destination is the package
// dir io/yaver/mobile/car under the app's kotlin/java source root.
function withNativeCarSources(config) {
  return withDangerousMod(config, [
    "android",
    (cfg) => {
      const root = cfg.modRequest.projectRoot;
      const src = path.join(root, "native-androidauto", "android");
      const pkgDir = NATIVE_PACKAGE.split(".").join(path.sep);
      // Expo RN apps put MainApplication.kt under
      // app/src/main/java/<pkg>/; we place the car package as a sibling.
      const destDir = path.join(
        cfg.modRequest.platformProjectRoot,
        "app",
        "src",
        "main",
        "java",
        pkgDir,
      );
      fs.mkdirSync(destDir, { recursive: true });
      for (const f of NATIVE_SOURCES) {
        const from = path.join(src, f);
        if (fs.existsSync(from)) fs.copyFileSync(from, path.join(destDir, f));
      }
      return cfg;
    },
  ]);
}

// ---- Android: register the reply <receiver> in the manifest ---------------
function withCarReplyReceiver(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.receiver = app.receiver || [];
    const exists = app.receiver.some(
      (r) => r.$ && r.$["android:name"] === REPLY_RECEIVER_NAME,
    );
    if (!exists) {
      app.receiver.push({
        $: {
          "android:name": REPLY_RECEIVER_NAME,
          "android:exported": "false",
        },
      });
    }
    return cfg;
  });
}

// ---- Android: add YaverCarMessagingPackage() to MainApplication -----------
// Inserts the package into the getPackages() list returned by the generated
// MainApplication.kt. Idempotent: skips if already present.
function withCarPackageRegistration(config) {
  return withMainApplication(config, (cfg) => {
    let contents = cfg.modResults.contents;
    const importLine = `import ${NATIVE_PACKAGE}.YaverCarMessagingPackage`;
    if (!contents.includes(importLine)) {
      // Add the import after the package declaration line.
      contents = contents.replace(
        /(^package [^\n]+\n)/m,
        `$1${importLine}\n`,
      );
    }
    if (!contents.includes("YaverCarMessagingPackage()")) {
      // Expo's RN template builds packages via PackageList(this).packages then
      // adds custom ones in a `.apply { add(...) }` block. Hook that block.
      if (/PackageList\(this\)\.packages\.apply\s*\{/.test(contents)) {
        contents = contents.replace(
          /(PackageList\(this\)\.packages\.apply\s*\{)/,
          `$1\n              add(YaverCarMessagingPackage())`,
        );
      } else if (/val packages = PackageList\(this\)\.packages/.test(contents)) {
        // Older template: mutate the list right after it's created.
        contents = contents.replace(
          /(val packages = PackageList\(this\)\.packages\n)/,
          `$1            packages.add(YaverCarMessagingPackage())\n`,
        );
      }
      // If neither shape matches we leave a marker so the human finisher can
      // wire it; the JS side still falls back to expo-notifications.
    }
    cfg.modResults.contents = contents;
    return cfg;
  });
}

module.exports = function withAndroidAutoMessaging(config) {
  config = withCarAppMetaData(config);
  config = withAutomotiveAppDescResource(config);
  config = withNativeCarSources(config);
  config = withCarReplyReceiver(config);
  config = withCarPackageRegistration(config);
  return config;
};

module.exports.CAR_APP_META_NAME = CAR_APP_META_NAME;
module.exports.CAR_APP_DESC_RESOURCE = CAR_APP_DESC_RESOURCE;
module.exports.AUTOMOTIVE_APP_DESC_XML = AUTOMOTIVE_APP_DESC_XML;
module.exports.NATIVE_PACKAGE = NATIVE_PACKAGE;
module.exports.NATIVE_SOURCES = NATIVE_SOURCES;
module.exports.REPLY_RECEIVER_NAME = REPLY_RECEIVER_NAME;
