import { router } from "expo-router";
import React from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useColors } from "../../src/context/ThemeContext";
import { AppBackButton } from "../../src/components/AppBackButton";

export default function PrivacyPolicyScreen() {
  const c = useColors();

  return (
    <SafeAreaView style={[styles.safeArea, { backgroundColor: c.bg }]}>
      <View style={[styles.header, { borderBottomColor: c.border }]}>
        <AppBackButton onPress={() => router.back()} textStyle={styles.backButton} />
        <Text style={[styles.headerTitle, { color: c.textPrimary }]}>Privacy Policy</Text>
        <View style={styles.headerSpacer} />
      </View>
      <ScrollView style={styles.container} contentContainerStyle={styles.content}>
        <Text style={[styles.lastUpdated, { color: c.textMuted }]}>Last updated: March 12, 2026</Text>

        <Text style={[styles.body, { color: c.textSecondary }]}>
          Yaver is a peer-to-peer development tool that lets you use Claude AI from any device, connecting directly to your development machines. This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of your information when you use the Service and tells you about your privacy rights and how the law protects you.
        </Text>
        <Text style={[styles.body, { color: c.textSecondary }]}>
          We use your Personal Data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.
        </Text>

        <Text style={[styles.sectionTitle, { color: c.textPrimary, borderBottomColor: c.border }]}>Interpretation and Definitions</Text>

        <Text style={[styles.subTitle, { color: c.textPrimary }]}>Interpretation</Text>
        <Text style={[styles.body, { color: c.textSecondary }]}>
          The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </Text>

        <Text style={[styles.subTitle, { color: c.textPrimary }]}>Definitions</Text>
        <Text style={[styles.body, { color: c.textSecondary }]}>For the purposes of this Privacy Policy:</Text>
        {[
          { term: "Account", def: "means a unique account created for you to access our Service or parts of our Service." },
          { term: "Application", def: "means the software programs provided by the Company, including the Yaver mobile app, desktop agent, and CLI tool." },
          { term: "Company", def: '(referred to as either "the Company", "We", "Us", or "Our" in this Agreement) refers to SIMKAB ELEKTRIK, Yunus Emre Mah. Adalar Sokak No:12 Sancaktepe/Istanbul.' },
          { term: "Country", def: "refers to: Turkey" },
          { term: "Device", def: "means any device that can access the Service such as a computer, a cellphone, or a digital tablet." },
          { term: "Personal Data", def: "is any information that relates to an identified or identifiable individual." },
          { term: "Service", def: "refers to the Application or the Website or both." },
          { term: "Usage Data", def: "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself." },
          { term: "Website", def: "refers to Yaver, accessible from yaver.io." },
          { term: "You", def: "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service." },
        ].map((item) => (
          <Text key={item.term} style={[styles.bullet, { color: c.textSecondary }]}>
            {"\u2022 "}<Text style={{ color: c.textPrimary, fontWeight: "600" }}>{item.term}</Text> {item.def}
          </Text>
        ))}

        <Text style={[styles.sectionTitle, { color: c.textPrimary, borderBottomColor: c.border }]}>Privacy-First Architecture</Text>
        <Text style={[styles.body, { color: c.textSecondary }]}>
          Yaver is designed with a privacy-first, peer-to-peer architecture. Your code, task data, prompts, and AI outputs flow directly between your devices over encrypted connections. Our servers are used only for authentication and device discovery -- we never see, store, or process your code or task content.
        </Text>
        {[
          "No code is stored on our servers",
          "No task data or AI output passes through our infrastructure",
          "No logs of your prompts or responses are captured",
          "Device-to-device communication is end-to-end encrypted",
        ].map((item) => (
          <Text key={item} style={[styles.bullet, { color: c.textSecondary }]}>{"\u2022 "}{item}</Text>
        ))}

        <Text style={[styles.sectionTitle, { color: c.textPrimary, borderBottomColor: c.border }]}>Collecting and Using Your Personal Data</Text>

        <Text style={[styles.subTitle, { color: c.textPrimary }]}>Personal Data</Text>
        <Text style={[styles.body, { color: c.textSecondary }]}>
          While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. This may include:
        </Text>
        {["Email address", "Name (as provided by your authentication provider)", "Usage Data"].map((item) => (
          <Text key={item} style={[styles.bullet, { color: c.textSecondary }]}>{"\u2022 "}{item}</Text>
        ))}

        <Text style={[styles.subTitle, { color: c.textPrimary }]}>Usage Data</Text>
        <Text style={[styles.body, { color: c.textSecondary }]}>
          Usage Data is collected automatically when using the Service. This may include your Device's Internet Protocol address, browser type, the pages of our Service that you visit, the time and date of your visit, unique device identifiers, and other diagnostic data.
        </Text>

        <Text style={[styles.subTitle, { color: c.textPrimary }]}>Device Registration Data</Text>
        <Text style={[styles.body, { color: c.textSecondary }]}>
          When you register a device with Yaver, we store basic device metadata (device name, platform, and network address) solely for the purpose of enabling peer discovery between your devices. This data is used only to help your devices find each other and is not shared with third parties.
        </Text>

        <Text style={[styles.subTitle, { color: c.textPrimary }]}>Use of Your Personal Data</Text>
        <Text style={[styles.body, { color: c.textSecondary }]}>The Company may use Personal Data for the following purposes:</Text>
        {[
          "To provide and maintain our Service, including authentication and device discovery.",
          "To manage your Account and registration as a user of the Service.",
          "To contact you by email regarding updates, security notices, or administrative messages.",
          "To manage your requests and provide support.",
          "For analytics: to understand usage patterns and improve the Service.",
        ].map((item) => (
          <Text key={item} style={[styles.bullet, { color: c.textSecondary }]}>{"\u2022 "}{item}</Text>
        ))}

        <Text style={[styles.subTitle, { color: c.textPrimary }]}>Retention of Your Personal Data</Text>
        <Text style={[styles.body, { color: c.textSecondary }]}>
          The Company will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our agreements and policies.
        </Text>

        <Text style={[styles.sectionTitle, { color: c.textPrimary, borderBottomColor: c.border }]}>Disclosure of Your Personal Data</Text>

        <Text style={[styles.subTitle, { color: c.textPrimary }]}>Business Transactions</Text>
        <Text style={[styles.body, { color: c.textSecondary }]}>
          If the Company is involved in a merger, acquisition, or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.
        </Text>

        <Text style={[styles.subTitle, { color: c.textPrimary }]}>Law Enforcement</Text>
        <Text style={[styles.body, { color: c.textSecondary }]}>
          Under certain circumstances, the Company may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.
        </Text>

        <Text style={[styles.sectionTitle, { color: c.textPrimary, borderBottomColor: c.border }]}>Security of Your Personal Data</Text>
        <Text style={[styles.body, { color: c.textSecondary }]}>
          The security of your Personal Data is important to us. Yaver's peer-to-peer architecture means your code and task data never pass through our servers. For authentication data that we do handle, we use commercially acceptable means to protect it. However, no method of transmission over the Internet or electronic storage is 100% secure.
        </Text>

        <Text style={[styles.sectionTitle, { color: c.textPrimary, borderBottomColor: c.border }]}>Account Deletion</Text>
        <Text style={[styles.body, { color: c.textSecondary }]}>
          You may delete your account at any time through the mobile app settings or by contacting us. When you delete your account, we will permanently remove your authentication data, device registrations, and any associated personal information from our servers.
        </Text>

        <Text style={[styles.sectionTitle, { color: c.textPrimary, borderBottomColor: c.border }]}>Children's Privacy</Text>
        <Text style={[styles.body, { color: c.textSecondary }]}>
          Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.
        </Text>

        <Text style={[styles.sectionTitle, { color: c.textPrimary, borderBottomColor: c.border }]}>Changes to this Privacy Policy</Text>
        <Text style={[styles.body, { color: c.textSecondary }]}>
          We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date. You are advised to review this Privacy Policy periodically for any changes.
        </Text>

        <Text style={[styles.sectionTitle, { color: c.textPrimary, borderBottomColor: c.border }]}>Contact Us</Text>
        <Text style={[styles.body, { color: c.textSecondary }]}>
          If you have any questions about this Privacy Policy, you can contact us:
        </Text>
        <Text style={[styles.bullet, { color: c.textSecondary }]}>{"\u2022 "}Email: kivanc.cakmak@simkab.com</Text>

        <View style={[styles.footer, { borderTopColor: c.border }]}>
          <Text style={[styles.footerText, { color: c.textMuted }]}>
            SIMKAB ELEKTRIK {"\u2014"} Yunus Emre Mah. Adalar Sokak No:12, Sancaktepe, Istanbul, Turkey
          </Text>
          <Text style={[styles.footerText, { color: c.textMuted }]}>
            Copyright {"\u00A9"} {new Date().getFullYear()} Yaver. All Rights Reserved.
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  backButton: { fontSize: 16 },
  headerTitle: { fontSize: 17, fontWeight: "600" },
  headerSpacer: { width: 40 },
  container: { flex: 1 },
  content: { padding: 16, paddingBottom: 40 },
  lastUpdated: { fontSize: 12, marginBottom: 16 },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    marginTop: 28,
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
  },
  subTitle: {
    fontSize: 14,
    fontWeight: "600",
    marginTop: 16,
    marginBottom: 8,
  },
  body: {
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 8,
  },
  bullet: {
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 4,
    paddingLeft: 8,
  },
  footer: {
    marginTop: 32,
    paddingTop: 16,
    borderTopWidth: 1,
  },
  footerText: { fontSize: 11, marginBottom: 4 },
});
