import { darkTokens, lightTokens } from "../theme/tokens";

export type ThemeColors = {
  bg: string;
  bgCard: string;
  bgCardElevated: string;
  bgInput: string;
  bgTabBar: string;
  border: string;
  borderStrong: string;
  borderSubtle: string;
  divider: string;
  textPrimary: string;
  textSecondary: string;
  textMuted: string;
  textTertiary: string;
  textDisabled: string;
  textInverse: string;
  accent: string;
  accentDim: string;
  accentSoft: string;
  success: string;
  successBg: string;
  successBorder: string;
  info: string;
  infoBg: string;
  infoBorder: string;
  error: string;
  errorBg: string;
  errorBorder: string;
  warn: string;
  warnBg: string;
  warnBorder: string;
  neutral: string;
  neutralBg: string;
  neutralBorder: string;
  shadowSm: string;
  shadowMd: string;
  tabActive: string;
  tabInactive: string;
  surface: string;
  surfaceElevated: string;
  surfaceMuted: string;
  brandPrimary: string;
  brandPrimarySoft: string;
};

export const DarkColors: ThemeColors = {
  bg: darkTokens.background,
  bgCard: darkTokens.surface,
  bgCardElevated: darkTokens.surfaceElevated,
  bgInput: darkTokens.surfaceMuted,
  bgTabBar: darkTokens.background,
  border: darkTokens.border,
  borderStrong: darkTokens.borderStrong,
  borderSubtle: darkTokens.divider,
  divider: darkTokens.divider,
  textPrimary: darkTokens.textPrimary,
  textSecondary: darkTokens.textSecondary,
  textMuted: darkTokens.textTertiary,
  textTertiary: darkTokens.textTertiary,
  textDisabled: darkTokens.textDisabled,
  textInverse: "#000000",
  accent: darkTokens.brandPrimary,
  accentDim: darkTokens.brandPrimaryHover,
  accentSoft: darkTokens.brandPrimarySoft,
  success: darkTokens.statusSuccess,
  successBg: darkTokens.statusSuccessSoft,
  successBorder: darkTokens.statusSuccess,
  info: darkTokens.statusInfo,
  infoBg: darkTokens.statusInfoSoft,
  infoBorder: darkTokens.statusInfo,
  error: darkTokens.statusError,
  errorBg: darkTokens.statusErrorSoft,
  errorBorder: darkTokens.statusError,
  warn: darkTokens.statusWarning,
  warnBg: darkTokens.statusWarningSoft,
  warnBorder: darkTokens.statusWarning,
  neutral: darkTokens.statusNeutral,
  neutralBg: darkTokens.statusNeutralSoft,
  neutralBorder: darkTokens.statusNeutral,
  shadowSm: darkTokens.shadowSm,
  shadowMd: darkTokens.shadowMd,
  tabActive: darkTokens.textPrimary,
  tabInactive: darkTokens.textTertiary,
  surface: darkTokens.surface,
  surfaceElevated: darkTokens.surfaceElevated,
  surfaceMuted: darkTokens.surfaceMuted,
  brandPrimary: darkTokens.brandPrimary,
  brandPrimarySoft: darkTokens.brandPrimarySoft,
};

export const LightColors: ThemeColors = {
  bg: lightTokens.background,
  bgCard: lightTokens.surface,
  bgCardElevated: lightTokens.surfaceElevated,
  bgInput: lightTokens.surfaceMuted,
  bgTabBar: lightTokens.surface,
  border: lightTokens.border,
  borderStrong: lightTokens.borderStrong,
  borderSubtle: lightTokens.divider,
  divider: lightTokens.divider,
  textPrimary: lightTokens.textPrimary,
  textSecondary: lightTokens.textSecondary,
  textMuted: lightTokens.textTertiary,
  textTertiary: lightTokens.textTertiary,
  textDisabled: lightTokens.textDisabled,
  textInverse: "#ffffff",
  accent: lightTokens.brandPrimary,
  accentDim: lightTokens.brandPrimaryHover,
  accentSoft: lightTokens.brandPrimarySoft,
  success: lightTokens.statusSuccess,
  successBg: lightTokens.statusSuccessSoft,
  successBorder: lightTokens.statusSuccess,
  info: lightTokens.statusInfo,
  infoBg: lightTokens.statusInfoSoft,
  infoBorder: lightTokens.statusInfo,
  error: lightTokens.statusError,
  errorBg: lightTokens.statusErrorSoft,
  errorBorder: lightTokens.statusError,
  warn: lightTokens.statusWarning,
  warnBg: lightTokens.statusWarningSoft,
  warnBorder: lightTokens.statusWarning,
  neutral: lightTokens.statusNeutral,
  neutralBg: lightTokens.statusNeutralSoft,
  neutralBorder: lightTokens.statusNeutral,
  shadowSm: lightTokens.shadowSm,
  shadowMd: lightTokens.shadowMd,
  tabActive: lightTokens.textPrimary,
  tabInactive: lightTokens.textTertiary,
  surface: lightTokens.surface,
  surfaceElevated: lightTokens.surfaceElevated,
  surfaceMuted: lightTokens.surfaceMuted,
  brandPrimary: lightTokens.brandPrimary,
  brandPrimarySoft: lightTokens.brandPrimarySoft,
};
