services:
    convex:
        image: ghcr.io/get-convex/convex-backend:latest
        port: 3210
        console_port: 3211
        env:
            CONVEX_SITE_URL: http://127.0.0.1:3211
            INSTANCE_NAME: yaver-local
        volume: yaver-convex-data
    convex-dashboard:
        image: ghcr.io/get-convex/convex-dashboard:latest
        port: 6791
        env:
            NEXT_PUBLIC_DEPLOYMENT_URL: http://127.0.0.1:3210
    minio:
        image: minio/minio
        port: 9000
        console_port: 9001
        env:
            MINIO_ROOT_PASSWORD: minioadmin
            MINIO_ROOT_USER: minioadmin
        volume: yaver-minio-data
        command: server /data --console-address :9001
