import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy - Yaver",
};

export default function PrivacyPolicyPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16 md:py-24">
      <div className="mb-8">
        <Link href="/" className="text-sm text-surface-500 hover:text-surface-300">
          &larr; Back to Home
        </Link>
      </div>

      <h1 className="mb-2 text-3xl font-bold text-surface-50">Privacy Policy</h1>
      <p className="mb-12 text-sm text-surface-500">Last updated: March 12, 2026</p>

      <div className="prose-legal space-y-6 text-sm leading-relaxed text-surface-400">
        <p>
          Yaver is a peer-to-peer development tool that lets you use Claude AI from any device,
          connecting directly to your development machines. This Privacy Policy describes our
          policies and procedures on the collection, use, and disclosure of your information
          when you use the Service and tells you about your privacy rights and how the law
          protects you.
        </p>
        <p>
          We use your Personal Data to provide and improve the Service. By using the Service,
          you agree to the collection and use of information in accordance with this Privacy Policy.
        </p>

        <h2 className="!mt-10 border-b border-surface-800 pb-2 text-lg font-semibold text-surface-100">
          Interpretation and Definitions
        </h2>

        <h3 className="!mt-6 text-base font-semibold text-surface-200">Interpretation</h3>
        <p>
          The words of which the initial letter is capitalized have meanings defined under the
          following conditions. The following definitions shall have the same meaning regardless
          of whether they appear in singular or in plural.
        </p>

        <h3 className="!mt-6 text-base font-semibold text-surface-200">Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <ul className="list-disc space-y-2 pl-6">
          <li><strong className="text-surface-300">Account</strong> means a unique account created for you to access our Service or parts of our Service.</li>
          <li><strong className="text-surface-300">Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &ldquo;control&rdquo; means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.</li>
          <li><strong className="text-surface-300">Application</strong> means the software programs provided by the Company, including the Yaver mobile app, desktop agent, and CLI tool.</li>
          <li><strong className="text-surface-300">Company</strong> (referred to as either &ldquo;the Company&rdquo;, &ldquo;We&rdquo;, &ldquo;Us&rdquo;, or &ldquo;Our&rdquo; in this Agreement) refers to SIMKAB ELEKTRIK, Yunus Emre Mah. Adalar Sokak No:12 Sancaktepe/Istanbul.</li>
          <li><strong className="text-surface-300">Country</strong> refers to: Turkey</li>
          <li><strong className="text-surface-300">Device</strong> means any device that can access the Service such as a computer, a cellphone, or a digital tablet.</li>
          <li><strong className="text-surface-300">Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
          <li><strong className="text-surface-300">Service</strong> refers to the Application or the Website or both.</li>
          <li><strong className="text-surface-300">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
          <li><strong className="text-surface-300">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
          <li><strong className="text-surface-300">Website</strong> refers to Yaver, accessible from <a href="https://yaver.io" className="text-indigo-400 hover:text-indigo-700 dark:hover:text-indigo-300">yaver.io</a>.</li>
          <li><strong className="text-surface-300">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service.</li>
        </ul>

        <h2 className="!mt-10 border-b border-surface-800 pb-2 text-lg font-semibold text-surface-100">
          Privacy-First Architecture
        </h2>
        <p>
          Yaver is designed with a privacy-first, peer-to-peer architecture. Your code, task data,
          prompts, and AI outputs flow directly between your devices over encrypted connections.
          Our servers are used <strong className="text-surface-300">only</strong> for authentication
          and device discovery — we never see, store, or process your code or task content.
        </p>
        <ul className="list-disc space-y-2 pl-6">
          <li>No code is stored on our servers</li>
          <li>No task data or AI output passes through our infrastructure</li>
          <li>No logs of your prompts or responses are captured</li>
          <li>Device-to-device communication is end-to-end encrypted</li>
        </ul>

        <h2 className="!mt-10 border-b border-surface-800 pb-2 text-lg font-semibold text-surface-100">
          Collecting and Using Your Personal Data
        </h2>

        <h3 className="!mt-6 text-base font-semibold text-surface-200">Types of Data Collected</h3>

        <h4 className="!mt-4 text-sm font-semibold text-surface-200">Personal Data</h4>
        <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. This may include:</p>
        <ul className="list-disc space-y-2 pl-6">
          <li>Email address</li>
          <li>Name (as provided by your authentication provider)</li>
          <li>Usage Data</li>
        </ul>

        <h4 className="!mt-4 text-sm font-semibold text-surface-200">Usage Data</h4>
        <p>
          Usage Data is collected automatically when using the Service. This may include your
          Device&apos;s Internet Protocol address, browser type, the pages of our Service that you
          visit, the time and date of your visit, unique device identifiers, and other diagnostic data.
        </p>

        <h4 className="!mt-4 text-sm font-semibold text-surface-200">Device Registration Data</h4>
        <p>
          When you register a device with Yaver, we store basic device metadata (device name,
          platform, and network address) solely for the purpose of enabling peer discovery between
          your devices. This data is used only to help your devices find each other and is not
          shared with third parties.
        </p>

        <h3 className="!mt-6 text-base font-semibold text-surface-200">Use of Your Personal Data</h3>
        <p>The Company may use Personal Data for the following purposes:</p>
        <ul className="list-disc space-y-2 pl-6">
          <li>To provide and maintain our Service, including authentication and device discovery.</li>
          <li>To manage your Account and registration as a user of the Service.</li>
          <li>To contact you by email regarding updates, security notices, or administrative messages.</li>
          <li>To manage your requests and provide support.</li>
          <li>For analytics: to understand usage patterns and improve the Service.</li>
        </ul>

        <p>We may share your personal information in the following situations:</p>
        <ul className="list-disc space-y-2 pl-6">
          <li><strong className="text-surface-300">With Service Providers:</strong> We may share your information with Service Providers to monitor and analyze the use of our Service.</li>
          <li><strong className="text-surface-300">For business transfers:</strong> We may share your information in connection with any merger, sale of Company assets, financing, or acquisition.</li>
          <li><strong className="text-surface-300">With your consent:</strong> We may disclose your personal information for any other purpose with your consent.</li>
        </ul>

        <h3 className="!mt-6 text-base font-semibold text-surface-200">Retention of Your Personal Data</h3>
        <p>
          The Company will retain your Personal Data only for as long as is necessary for the
          purposes set out in this Privacy Policy. We will retain and use your Personal Data to
          the extent necessary to comply with our legal obligations, resolve disputes, and enforce
          our agreements and policies.
        </p>

        <h3 className="!mt-6 text-base font-semibold text-surface-200">Transfer of Your Personal Data</h3>
        <p>
          Your information, including Personal Data, is processed at the Company&apos;s operating
          offices and in any other places where the parties involved in the processing are located.
          Your consent to this Privacy Policy followed by your submission of such information
          represents your agreement to that transfer.
        </p>

        <h2 className="!mt-10 border-b border-surface-800 pb-2 text-lg font-semibold text-surface-100">
          Disclosure of Your Personal Data
        </h2>

        <h3 className="!mt-6 text-base font-semibold text-surface-200">Business Transactions</h3>
        <p>
          If the Company is involved in a merger, acquisition, or asset sale, your Personal Data
          may be transferred. We will provide notice before your Personal Data is transferred and
          becomes subject to a different Privacy Policy.
        </p>

        <h3 className="!mt-6 text-base font-semibold text-surface-200">Law Enforcement</h3>
        <p>
          Under certain circumstances, the Company may be required to disclose your Personal Data
          if required to do so by law or in response to valid requests by public authorities.
        </p>

        <h3 className="!mt-6 text-base font-semibold text-surface-200">Other Legal Requirements</h3>
        <p>
          The Company may disclose your Personal Data in the good faith belief that such action
          is necessary to: comply with a legal obligation; protect and defend the rights or property
          of the Company; prevent or investigate possible wrongdoing; protect the personal safety of
          users or the public; or protect against legal liability.
        </p>

        <h2 className="!mt-10 border-b border-surface-800 pb-2 text-lg font-semibold text-surface-100">
          Security of Your Personal Data
        </h2>
        <p>
          The security of your Personal Data is important to us. Yaver&apos;s peer-to-peer architecture
          means your code and task data never pass through our servers. For authentication data that
          we do handle, we use commercially acceptable means to protect it. However, no method of
          transmission over the Internet or electronic storage is 100% secure.
        </p>

        <h2 className="!mt-10 border-b border-surface-800 pb-2 text-lg font-semibold text-surface-100">
          Account Deletion
        </h2>
        <p>
          You may delete your account at any time through the mobile app settings or by contacting
          us. When you delete your account, we will permanently remove your authentication data,
          device registrations, and any associated personal information from our servers.
        </p>

        <h2 className="!mt-10 border-b border-surface-800 pb-2 text-lg font-semibold text-surface-100">
          Personal Agent Gateway &amp; Phone Clone
        </h2>
        <p>
          Yaver can act on your behalf inside apps that have no public API by driving a{" "}
          <strong className="text-surface-300">clone</strong> &mdash; either a containerized Android
          instance (redroid) on a machine you control, or a spare physical Android phone you own.
          The clone signs in to <em>your own</em> accounts so the AI can read and act for you. This
          is optional and off until you set it up. A few things we want to be explicit about:
        </p>
        <ul className="list-disc space-y-2 pl-6">
          <li>
            <strong className="text-surface-300">It is peer-to-peer and self-hosted.</strong> The
            clone runs on your own device or your own machine. Your credentials, sessions, and the
            data the gateway reads flow directly between your devices over Yaver&rsquo;s P2P transport
            (direct LAN / Tailscale / self-hostable relay). They do not pass through, and are never
            stored on, our backend (Convex).
          </li>
          <li>
            <strong className="text-surface-300">It is open source.</strong> The entire gateway
            framework &mdash; connectors, the consent and audit layer, app provisioning, and the
            device-driving engines &mdash; is in the public Yaver source on GitHub. You can read
            exactly what it does, and self-host every part of it.
          </li>
          <li>
            <strong className="text-surface-300">It is local-first and opt-in.</strong> Your app
            list, your connector credentials (in the encrypted vault), and the local audit ledger
            live on your devices. Each capability &mdash; sharing your installed-app list with a
            clone, auto-forwarding a one-time code, or letting a clone read its own SMS inbox &mdash;
            is a separate consent you grant, recorded locally and revocable.
          </li>
          <li>
            <strong className="text-surface-300">We never store your secrets.</strong> Vault values,
            tokens, one-time codes, message contents, and the contents of the apps the gateway reads
            are forbidden from our backend by design and enforced by automated tests. A one-time code
            your phone forwards is relayed straight to the waiting sign-in and is never persisted.
          </li>
          <li>
            <strong className="text-surface-300">Two-factor authentication is relayed, not
            bypassed.</strong> When a sign-in needs a code or an approval, you still receive and
            approve it yourself &mdash; Yaver only carries your answer to the clone. We do not solve
            CAPTCHAs, defeat device attestation, or circumvent any security control. If a service
            blocks automated access, Yaver stops.
          </li>
          <li>
            <strong className="text-surface-300">You only ever act on your own accounts.</strong> The
            gateway is for automating tasks you already do by hand, on services where you hold the
            account. It is not for accessing anyone else&rsquo;s data or systems.
          </li>
          <li>
            <strong className="text-surface-300">A self-driving clone uses Android Accessibility on
            that device only.</strong> If you run the clone on a spare phone with no separate host,
            you enable Yaver&rsquo;s Accessibility service once in that phone&rsquo;s settings so the
            app can tap and read its own screen. That capability controls only the clone device you
            own, over a loopback connection that is never network-exposed, and is used solely to
            drive your own logged-in apps.
          </li>
        </ul>

        <h2 className="!mt-10 border-b border-surface-800 pb-2 text-lg font-semibold text-surface-100">
          Children&apos;s Privacy
        </h2>
        <p>
          Our Service does not address anyone under the age of 13. We do not knowingly collect
          personally identifiable information from anyone under the age of 13. If we become aware
          that we have collected Personal Data from anyone under 13 without verification of parental
          consent, we take steps to remove that information from our servers.
        </p>

        <h2 className="!mt-10 border-b border-surface-800 pb-2 text-lg font-semibold text-surface-100">
          Links to Other Websites
        </h2>
        <p>
          Our Service may contain links to other websites that are not operated by us. We strongly
          advise you to review the Privacy Policy of every site you visit. We have no control over
          and assume no responsibility for the content, privacy policies, or practices of any third
          party sites or services.
        </p>

        <h2 className="!mt-10 border-b border-surface-800 pb-2 text-lg font-semibold text-surface-100">
          Changes to this Privacy Policy
        </h2>
        <p>
          We may update our Privacy Policy from time to time. We will notify you of any changes by
          posting the new Privacy Policy on this page and updating the &ldquo;Last updated&rdquo;
          date. You are advised to review this Privacy Policy periodically for any changes.
        </p>

        <h2 className="!mt-10 border-b border-surface-800 pb-2 text-lg font-semibold text-surface-100">
          Contact Us
        </h2>
        <p>If you have any questions about this Privacy Policy, you can contact us:</p>
        <ul className="list-disc space-y-2 pl-6">
          <li>Email: <a href="mailto:kivanc.cakmak@simkab.com" className="text-indigo-400 hover:text-indigo-700 dark:hover:text-indigo-300">kivanc.cakmak@simkab.com</a></li>
        </ul>

        <div className="!mt-16 border-t border-surface-800 pt-6 text-xs text-surface-600">
          <p>SIMKAB ELEKTRIK &mdash; Yunus Emre Mah. Adalar Sokak No:12, Sancaktepe, Istanbul, Turkey</p>
          <p className="mt-1">Copyright &copy; {new Date().getFullYear()} Yaver. All Rights Reserved.</p>
        </div>
      </div>
    </div>
  );
}
