package main

// caps_generate.go — turn the inferred capability plan into actual CONFIG.
//
// We generate into app.json / Expo config (ios.infoPlist usage strings +
// android.permissions), NOT raw Info.plist/AndroidManifest — those are
// regenerated by `expo prebuild --clean` and any hand-edit is lost. Merging is
// ADDITIVE + idempotent and PRESERVES the user's existing custom usage strings
// (never clobbers copy they refined). Entitlements are reported, not
// auto-written: they also need App-ID enablement (`yaver keys`) and per-key
// shapes, so the user/AI sets those deliberately.

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
)

func asMap(parent map[string]interface{}, key string) map[string]interface{} {
	if existing, ok := parent[key].(map[string]interface{}); ok {
		return existing
	}
	m := map[string]interface{}{}
	parent[key] = m
	return m
}

func asStringSlice(v interface{}) []string {
	switch t := v.(type) {
	case []string:
		return append([]string(nil), t...)
	case []interface{}:
		out := make([]string, 0, len(t))
		for _, e := range t {
			if s, ok := e.(string); ok {
				out = append(out, s)
			}
		}
		return out
	}
	return nil
}

// mergeManifestIntoAppConfig adds the plan's iOS usage strings + Android
// permissions into an app.json structure. Returns the updated config and the
// list of changes made (empty ⇒ already up to date).
func mergeManifestIntoAppConfig(cfg map[string]interface{}, plan ManifestPlan) (map[string]interface{}, []string) {
	var changes []string
	expo := asMap(cfg, "expo")

	// iOS Info.plist usage strings — add missing, preserve existing.
	ios := asMap(expo, "ios")
	infoPlist := asMap(ios, "infoPlist")
	keys := make([]string, 0, len(plan.IOSPlistUsage))
	for k := range plan.IOSPlistUsage {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		if _, exists := infoPlist[k]; !exists {
			infoPlist[k] = plan.IOSPlistUsage[k]
			changes = append(changes, "ios.infoPlist."+k)
		}
	}

	// Android permissions — union (don't drop the user's existing ones).
	android := asMap(expo, "android")
	perms := asStringSlice(android["permissions"])
	seen := map[string]bool{}
	for _, p := range perms {
		seen[p] = true
	}
	for _, p := range plan.AndroidPermissions {
		if !seen[p] {
			perms = append(perms, p)
			seen[p] = true
			changes = append(changes, "android.permissions += "+p)
		}
	}
	if len(perms) > 0 {
		sort.Strings(perms)
		android["permissions"] = perms
	}
	return cfg, changes
}

// runCapsGenerate prints (or --write merges) the Expo config additions.
func runCapsGenerate(args []string) {
	path := "."
	write := false
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--path":
			if i+1 < len(args) {
				path = args[i+1]
				i++
			}
		case "--write":
			write = true
		case "-h", "--help":
			fmt.Println("Usage: yaver caps generate [--path DIR] [--write]")
			fmt.Println("  Merge the inferred iOS usage strings + Android permissions into app.json.")
			fmt.Println("  Default prints the additions; --write applies them (preserving your edits).")
			return
		}
	}

	plan := buildManifestPlan(path)
	appJSONPath := filepath.Join(path, "app.json")
	cfg := map[string]interface{}{}
	if b, err := os.ReadFile(appJSONPath); err == nil {
		_ = json.Unmarshal(b, &cfg)
	}
	updated, changes := mergeManifestIntoAppConfig(cfg, plan)

	if len(changes) == 0 {
		fmt.Println("app.json already declares everything your code needs. ✓")
		if len(plan.IOSEntitlements) > 0 {
			fmt.Printf("  (Entitlements still to enable via `yaver keys`: %v)\n", plan.IOSEntitlements)
		}
		return
	}

	if !write {
		fmt.Println("Additions needed in app.json (run with --write to apply):")
		for _, c := range changes {
			fmt.Printf("  + %s\n", c)
		}
		if len(plan.IOSEntitlements) > 0 {
			fmt.Printf("\nEntitlements (set deliberately + enable on the App ID via `yaver keys`): %v\n", plan.IOSEntitlements)
		}
		return
	}

	out, err := json.MarshalIndent(updated, "", "  ")
	if err != nil {
		fmt.Fprintf(os.Stderr, "marshal app.json: %v\n", err)
		return
	}
	if err := os.WriteFile(appJSONPath, append(out, '\n'), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", appJSONPath, err)
		return
	}
	fmt.Printf("Updated %s (%d change(s)):\n", appJSONPath, len(changes))
	for _, c := range changes {
		fmt.Printf("  + %s\n", c)
	}
}
