package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"
)

// YaverDomain maps a hostname to an upstream (e.g. localhost:3000).
type YaverDomain struct {
	ID        string    `json:"id" yaml:"id"`
	Domain    string    `json:"domain" yaml:"domain"`
	Upstream  string    `json:"upstream" yaml:"upstream"` // host:port or full URL
	Static    string    `json:"static,omitempty" yaml:"static,omitempty"` // serve static dir
	CreatedAt time.Time `json:"createdAt" yaml:"createdAt"`
	Enabled   bool      `json:"enabled" yaml:"enabled"`
	DNSMode   string    `json:"dnsMode,omitempty" yaml:"dnsMode,omitempty"` // http, cloudflare
}

type domainStore struct {
	mu     sync.Mutex
	routes map[string]*YaverDomain // by domain
}

var domains = &domainStore{routes: map[string]*YaverDomain{}}

func domainsFile() string {
	base, _ := ConfigDir()
	return filepath.Join(base, "domains.json")
}

func loadDomainStore() {
	data, err := os.ReadFile(domainsFile())
	if err != nil {
		return
	}
	var list []*YaverDomain
	if json.Unmarshal(data, &list) != nil {
		return
	}
	domains.mu.Lock()
	defer domains.mu.Unlock()
	for _, r := range list {
		domains.routes[r.Domain] = r
	}
}

func persistDomainStore() error {
	domains.mu.Lock()
	list := make([]*YaverDomain, 0, len(domains.routes))
	for _, r := range domains.routes {
		list = append(list, r)
	}
	domains.mu.Unlock()
	sort.Slice(list, func(i, j int) bool { return list[i].Domain < list[j].Domain })
	data, _ := json.MarshalIndent(list, "", "  ")
	return os.WriteFile(domainsFile(), data, 0o644)
}

// AddDomain attaches a hostname to an upstream and regenerates Caddy config.
// Caddy picks up the change on SIGHUP and fetches Let's Encrypt certs automatically.
func AddDomain(domain, upstream, static, dnsMode string) (*YaverDomain, error) {
	domain = strings.TrimSpace(strings.ToLower(domain))
	if domain == "" {
		return nil, fmt.Errorf("domain required")
	}
	if upstream == "" && static == "" {
		return nil, fmt.Errorf("upstream or static required")
	}
	domains.mu.Lock()
	r := &YaverDomain{
		ID: fmt.Sprintf("dom_%d", time.Now().Unix()),
		Domain: domain, Upstream: upstream, Static: static,
		CreatedAt: time.Now(), Enabled: true, DNSMode: dnsMode,
	}
	domains.routes[domain] = r
	domains.mu.Unlock()
	if err := persistDomainStore(); err != nil {
		return nil, err
	}
	if err := RegenerateCaddyfile(); err != nil {
		AuditLog("", "domain_add", domain, upstream, "caddy-failed", err.Error(), "")
		return r, fmt.Errorf("domain saved but Caddy reload failed: %w", err)
	}
	AuditLog("", "domain_add", domain, upstream, "success", "", "")
	return r, nil
}

func RemoveDomain(domain string) error {
	domain = strings.TrimSpace(strings.ToLower(domain))
	domains.mu.Lock()
	delete(domains.routes, domain)
	domains.mu.Unlock()
	if err := persistDomainStore(); err != nil {
		return err
	}
	return RegenerateCaddyfile()
}

func ListDomains() []*YaverDomain {
	loadDomainStore()
	domains.mu.Lock()
	defer domains.mu.Unlock()
	out := make([]*YaverDomain, 0, len(domains.routes))
	for _, r := range domains.routes {
		out = append(out, r)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Domain < out[j].Domain })
	return out
}

// RegenerateCaddyfile writes .yaver/Caddyfile from the in-memory store and
// reloads Caddy via `caddy reload` (or starts it if not running).
func RegenerateCaddyfile() error {
	base, _ := ConfigDir()
	path := filepath.Join(base, "Caddyfile")
	var sb strings.Builder
	sb.WriteString("# Auto-generated by Yaver. Do not edit manually.\n")
	sb.WriteString("{\n  admin off\n}\n\n")
	for _, r := range ListDomains() {
		if !r.Enabled {
			continue
		}
		sb.WriteString(r.Domain + " {\n")
		if r.Static != "" {
			sb.WriteString("  root * " + r.Static + "\n")
			sb.WriteString("  file_server\n")
		}
		if r.Upstream != "" {
			up := r.Upstream
			if !strings.HasPrefix(up, "http") {
				up = "http://" + up
			}
			sb.WriteString("  reverse_proxy " + up + "\n")
		}
		sb.WriteString("  encode gzip zstd\n")
		sb.WriteString("}\n\n")
	}
	if err := os.WriteFile(path, []byte(sb.String()), 0o644); err != nil {
		return err
	}
	// Reload Caddy if it's running. Auto-install if missing.
	if _, err := exec.LookPath("caddy"); err != nil {
		if installErr := autoInstallCaddy(); installErr != nil {
			return fmt.Errorf("caddy not installed and auto-install failed: %w — try manually: brew install caddy (or see https://caddyserver.com/docs/install)", installErr)
		}
	}
	cmd := exec.Command("caddy", "reload", "--config", path)
	out, err := cmd.CombinedOutput()
	if err != nil {
		// Try starting.
		startCmd := exec.Command("caddy", "run", "--config", path, "--pidfile", filepath.Join(base, "caddy.pid"))
		startCmd.Stdout = os.Stdout
		startCmd.Stderr = os.Stderr
		if startErr := startCmd.Start(); startErr != nil {
			return fmt.Errorf("caddy reload: %w (output: %s); caddy start also failed: %v", err, out, startErr)
		}
		return nil
	}
	return nil
}

// ---- HTTP / MCP ----

func (s *HTTPServer) handleDomainList(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, map[string]interface{}{"domains": ListDomains()})
}

func (s *HTTPServer) handleDomainAdd(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		jsonError(w, http.StatusMethodNotAllowed, "POST only")
		return
	}
	var b struct {
		Domain   string `json:"domain"`
		Upstream string `json:"upstream"`
		Static   string `json:"static"`
		DNSMode  string `json:"dnsMode"`
	}
	_ = json.NewDecoder(r.Body).Decode(&b)
	rec, err := AddDomain(b.Domain, b.Upstream, b.Static, b.DNSMode)
	if err != nil {
		writeJSON(w, http.StatusOK, map[string]interface{}{"error": err.Error(), "record": rec})
		return
	}
	writeJSON(w, http.StatusOK, rec)
}

func (s *HTTPServer) handleDomainRemove(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		jsonError(w, http.StatusMethodNotAllowed, "POST only")
		return
	}
	var b struct{ Domain string `json:"domain"` }
	_ = json.NewDecoder(r.Body).Decode(&b)
	if err := RemoveDomain(b.Domain); err != nil {
		writeJSON(w, http.StatusOK, map[string]interface{}{"error": err.Error()})
		return
	}
	writeJSON(w, http.StatusOK, map[string]interface{}{"ok": true})
}
