package main

// init_project_feedback.go — auto-install the yaver-feedback-web SDK
// when init_project scaffolds a web stack (Next / Vite / SvelteKit /
// Remix). Mirrors what the mobile path does for RN projects: every
// scaffold ships with the floating bug-report widget already wired,
// so users don't go hunting for "how do I add the feedback thing".
//
// Two steps:
//   1. Append `yaver-feedback-web` to package.json.devDependencies
//      (no `npm install` here — the user runs that themselves; we
//      don't want a multi-minute network call inside init_project).
//   2. Drop a stub yaver-feedback.ts file next to src/ with the
//      init call, gated on NODE_ENV !== "production".
//
// The stub is intentionally framework-agnostic; the user wires the
// import into their root layout / _app / main.ts when they're ready.

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// isWebStackForFeedback returns true when the chosen init stack has a
// browser surface that could host the feedback SDK. Hono / Go / Python
// backends without a frontend return false.
func isWebStackForFeedback(stack string) bool {
	switch strings.ToLower(strings.TrimSpace(stack)) {
	case "nextjs", "next", "vite", "remix", "sveltekit", "svelte", "astro", "nuxt", "solid":
		return true
	}
	return false
}

// installWebFeedbackSDK adds the dep to package.json + writes the
// init stub. Returns a one-line next-step hint suitable for appending
// to InitProjectResult.NextSteps.
func installWebFeedbackSDK(dir string, _ InitProjectOpts) (string, error) {
	pkgPath := filepath.Join(dir, "package.json")
	raw, err := os.ReadFile(pkgPath)
	if err != nil {
		return "", fmt.Errorf("read package.json: %w", err)
	}
	var pkg map[string]interface{}
	if err := json.Unmarshal(raw, &pkg); err != nil {
		return "", fmt.Errorf("parse package.json: %w", err)
	}
	deps, _ := pkg["devDependencies"].(map[string]interface{})
	if deps == nil {
		deps = map[string]interface{}{}
	}
	// Pin to a recent published version. The runtime check on the SDK
	// side falls back to whatever's installed, so a minor drift between
	// the agent and the SDK is fine.
	if _, exists := deps["yaver-feedback-web"]; !exists {
		deps["yaver-feedback-web"] = "^0.4.8"
		pkg["devDependencies"] = deps
		out, _ := json.MarshalIndent(pkg, "", "  ")
		if werr := os.WriteFile(pkgPath, append(out, '\n'), 0o644); werr != nil {
			return "", werr
		}
	}

	// Write a framework-agnostic stub. The user imports it from their
	// root layout / _app.tsx / main.ts when they're ready.
	stubPath := filepath.Join(dir, "yaver-feedback.ts")
	if _, err := os.Stat(stubPath); err == nil {
		// Existing file — don't clobber.
		return "yaver-feedback-web installed (existing stub kept)", nil
	}
	if err := os.WriteFile(stubPath, []byte(webFeedbackStub), 0o644); err != nil {
		return "", err
	}
	return "import './yaver-feedback' in your root layout / _app.tsx to enable the bug-report widget", nil
}

const webFeedbackStub = `// yaver-feedback.ts — visual bug-report widget for this app.
//
// Generated by \"yaver init_project\". Import this from your root
// layout / _app.tsx / main.ts so the floating button shows up in dev
// builds. Production builds short-circuit via the env check below.
//
// Docs: https://github.com/kivanccakmak/yaver.io/tree/main/sdk/feedback/web

import { YaverFeedback } from 'yaver-feedback-web';

if (typeof window !== 'undefined' && process.env.NODE_ENV !== 'production') {
  YaverFeedback.init({
    trigger: 'floating-button',
    // The SDK auto-discovers a reachable yaver agent on the LAN. Set
    // an explicit agentUrl here if you need to override (e.g. for a
    // managed-cloud box reached via a tunnel).
  }).catch((err) => {
    // Don't crash the host app if the SDK fails to init — log only.
    console.warn('[yaver-feedback] init failed:', err);
  });
}
`
