package main

// meetings.go — public booking page + Google Calendar /
// Microsoft 365 integration. Replaces Calendly / Cal.com /
// SavvyCal for the solo dev who already has Google Workspace
// or O365. All credentials are reused from the existing
// EmailConfig (Gmail OAuth for Google, Azure tenant for O365) so
// the dev only authorises once.
//
// Flow:
//
//   1. Dev defines an event type: duration, availability rules,
//      where to host it (Google Meet or Microsoft Teams link
//      auto-generated by the calendar API).
//   2. Visitor hits yourname.com/meet/<slug> — public page
//      computes free slots from the dev's calendar and lists
//      the next N days.
//   3. Visitor picks a slot + enters name/email.
//   4. Agent creates a calendar event on the dev's calendar,
//      attaches the visitor, auto-creates the conferencing link
//      (conferenceData:{createRequest} on Google,
//      onlineMeeting on Graph), sends both sides a notification
//      via the existing SMTP relay.
//
// Nothing touches Convex.

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

// EventType is one bookable slot kind.
type EventType struct {
	Slug         string    `json:"slug"`
	Title        string    `json:"title"`
	DurationMin  int       `json:"durationMin"`
	Description  string    `json:"description,omitempty"`
	Provider     string    `json:"provider"` // "google" | "o365"
	Hosting      string    `json:"hosting"`  // "meet" | "teams" | "none"
	Availability []Avail   `json:"availability"`
	BufferMin    int       `json:"bufferMin,omitempty"` // pad after each booking
	DaysAhead    int       `json:"daysAhead,omitempty"` // default 14
	Location     string    `json:"location,omitempty"`
	CreatedAt    time.Time `json:"createdAt"`
}

// Avail is a weekly recurring window — e.g. Mon-Fri 09:00-17:00.
type Avail struct {
	Weekday   int    `json:"weekday"`   // 0=Sun..6=Sat
	StartTime string `json:"startTime"` // "09:00"
	EndTime   string `json:"endTime"`   // "17:00"
	Timezone  string `json:"timezone,omitempty"`
}

// Booking is one confirmed slot.
type Booking struct {
	ID         string    `json:"id"`
	EventSlug  string    `json:"eventSlug"`
	Name       string    `json:"name"`
	Email      string    `json:"email"`
	StartsAt   time.Time `json:"startsAt"`
	EndsAt     time.Time `json:"endsAt"`
	CreatedAt  time.Time `json:"createdAt"`
	JoinURL    string    `json:"joinUrl,omitempty"`
	CalEventID string    `json:"calEventId,omitempty"`
	Provider   string    `json:"provider"`
}

var (
	meetMu     sync.Mutex
	eventTypes []EventType
	bookings   []Booking
)

func meetingsFile() (string, error) {
	dir, err := ConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "meetings.json"), nil
}

func bookingsFile() (string, error) {
	dir, err := ConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "bookings.json"), nil
}

func loadMeetings() []EventType {
	meetMu.Lock()
	defer meetMu.Unlock()
	if eventTypes != nil {
		return eventTypes
	}
	p, _ := meetingsFile()
	data, err := os.ReadFile(p)
	if err != nil {
		eventTypes = []EventType{}
		return eventTypes
	}
	_ = json.Unmarshal(data, &eventTypes)
	return eventTypes
}

func saveMeetings() error {
	p, _ := meetingsFile()
	data, _ := json.MarshalIndent(eventTypes, "", "  ")
	return os.WriteFile(p, data, 0o600)
}

func loadBookings() []Booking {
	meetMu.Lock()
	defer meetMu.Unlock()
	if bookings != nil {
		return bookings
	}
	p, _ := bookingsFile()
	data, err := os.ReadFile(p)
	if err != nil {
		bookings = []Booking{}
		return bookings
	}
	_ = json.Unmarshal(data, &bookings)
	return bookings
}

func saveBookings() error {
	p, _ := bookingsFile()
	data, _ := json.MarshalIndent(bookings, "", "  ")
	return os.WriteFile(p, data, 0o600)
}

func findEventType(slug string) *EventType {
	list := loadMeetings()
	for i := range list {
		if list[i].Slug == slug {
			return &eventTypes[i]
		}
	}
	return nil
}

// --- slot computation ------------------------------------------------------

// computeSlots returns bookable start times over the event's
// DaysAhead window, excluding slots that collide with existing
// bookings. Pure-function so tests can pin a fake clock later.
func computeSlots(e *EventType, now time.Time) []time.Time {
	out := []time.Time{}
	days := e.DaysAhead
	if days <= 0 {
		days = 14
	}
	busy := []time.Time{}
	for _, b := range loadBookings() {
		if b.EventSlug == e.Slug {
			busy = append(busy, b.StartsAt)
		}
	}
	for d := 0; d < days; d++ {
		day := now.AddDate(0, 0, d)
		wd := int(day.Weekday())
		for _, a := range e.Availability {
			if a.Weekday != wd {
				continue
			}
			loc, _ := time.LoadLocation(a.Timezone)
			if loc == nil {
				loc = time.Local
			}
			sh, sm := parseHHMM(a.StartTime)
			eh, em := parseHHMM(a.EndTime)
			start := time.Date(day.Year(), day.Month(), day.Day(), sh, sm, 0, 0, loc)
			end := time.Date(day.Year(), day.Month(), day.Day(), eh, em, 0, 0, loc)
			step := time.Duration(e.DurationMin+e.BufferMin) * time.Minute
			for t := start; t.Add(time.Duration(e.DurationMin)*time.Minute).Before(end) || t.Add(time.Duration(e.DurationMin)*time.Minute).Equal(end); t = t.Add(step) {
				if t.Before(now.Add(1 * time.Hour)) {
					continue
				}
				collide := false
				for _, b := range busy {
					if b.Equal(t) {
						collide = true
						break
					}
				}
				if !collide {
					out = append(out, t)
				}
			}
		}
	}
	return out
}

func parseHHMM(s string) (int, int) {
	parts := strings.SplitN(s, ":", 2)
	var h, m int
	if len(parts) == 2 {
		fmt.Sscan(parts[0], &h)
		fmt.Sscan(parts[1], &m)
	}
	return h, m
}

// --- calendar integration --------------------------------------------------

// createGoogleEvent books the slot on the dev's primary Google
// calendar + attaches the visitor + requests a Google Meet link.
// Returns the calendar event ID + join URL.
func createGoogleEvent(cfg *EmailConfig, e *EventType, b *Booking) (string, string, error) {
	token, err := gmailAccess(cfg)
	if err != nil {
		return "", "", err
	}
	body := map[string]interface{}{
		"summary":     e.Title,
		"description": fmt.Sprintf("%s\n\nBooked via Yaver meetings", e.Description),
		"start":       map[string]interface{}{"dateTime": b.StartsAt.Format(time.RFC3339)},
		"end":         map[string]interface{}{"dateTime": b.EndsAt.Format(time.RFC3339)},
		"attendees":   []map[string]string{{"email": b.Email, "displayName": b.Name}},
	}
	if e.Hosting == "meet" {
		body["conferenceData"] = map[string]interface{}{
			"createRequest": map[string]interface{}{
				"requestId":             b.ID,
				"conferenceSolutionKey": map[string]string{"type": "hangoutsMeet"},
			},
		}
	}
	data, _ := json.Marshal(body)
	req, _ := http.NewRequest("POST", "https://www.googleapis.com/calendar/v3/calendars/primary/events?conferenceDataVersion=1&sendUpdates=all", strings.NewReader(string(data)))
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Content-Type", "application/json")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", "", err
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(resp.Body)
	if resp.StatusCode >= 300 {
		return "", "", fmt.Errorf("google calendar %d: %s", resp.StatusCode, string(raw))
	}
	var out struct {
		ID             string `json:"id"`
		ConferenceData struct {
			EntryPoints []struct {
				URI string `json:"uri"`
			} `json:"entryPoints"`
		} `json:"conferenceData"`
	}
	_ = json.Unmarshal(raw, &out)
	joinURL := ""
	if len(out.ConferenceData.EntryPoints) > 0 {
		joinURL = out.ConferenceData.EntryPoints[0].URI
	}
	return out.ID, joinURL, nil
}

// createGraphEvent books on the dev's O365 calendar and (if
// requested) creates an online Teams meeting.
func createGraphEvent(cfg *EmailConfig, e *EventType, b *Booking) (string, string, error) {
	token, err := graphAccess(cfg)
	if err != nil {
		return "", "", err
	}
	body := map[string]interface{}{
		"subject": e.Title,
		"body": map[string]interface{}{
			"contentType": "HTML",
			"content":     e.Description,
		},
		"start": map[string]string{"dateTime": b.StartsAt.Format(time.RFC3339), "timeZone": "UTC"},
		"end":   map[string]string{"dateTime": b.EndsAt.Format(time.RFC3339), "timeZone": "UTC"},
		"attendees": []map[string]interface{}{
			{"emailAddress": map[string]string{"address": b.Email, "name": b.Name}, "type": "required"},
		},
	}
	if e.Hosting == "teams" {
		body["isOnlineMeeting"] = true
		body["onlineMeetingProvider"] = "teamsForBusiness"
	}
	data, _ := json.Marshal(body)
	req, _ := http.NewRequest("POST", fmt.Sprintf("%s/users/%s/events", graphBase, url.PathEscape(cfg.SenderEmail)), strings.NewReader(string(data)))
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Content-Type", "application/json")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", "", err
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(resp.Body)
	if resp.StatusCode >= 300 {
		return "", "", fmt.Errorf("graph event %d: %s", resp.StatusCode, string(raw))
	}
	var out struct {
		ID            string `json:"id"`
		OnlineMeeting struct {
			JoinURL string `json:"joinUrl"`
		} `json:"onlineMeeting"`
	}
	_ = json.Unmarshal(raw, &out)
	return out.ID, out.OnlineMeeting.JoinURL, nil
}

// --- HTTP ------------------------------------------------------------------

func (s *HTTPServer) handleMeetings(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		jsonReply(w, http.StatusOK, map[string]interface{}{"ok": true, "eventTypes": loadMeetings()})
	case http.MethodPost:
		var e EventType
		if err := json.NewDecoder(r.Body).Decode(&e); err != nil {
			jsonError(w, http.StatusBadRequest, "invalid JSON")
			return
		}
		if e.Slug == "" || e.Title == "" {
			jsonError(w, http.StatusBadRequest, "slug and title required")
			return
		}
		if e.DurationMin <= 0 {
			e.DurationMin = 30
		}
		if e.DaysAhead <= 0 {
			e.DaysAhead = 14
		}
		e.CreatedAt = time.Now().UTC()
		current := loadMeetings()
		meetMu.Lock()
		eventTypes = append(current, e)
		_ = saveMeetings()
		meetMu.Unlock()
		jsonReply(w, http.StatusCreated, map[string]interface{}{"ok": true, "eventType": e})
	default:
		jsonError(w, http.StatusMethodNotAllowed, "use GET/POST")
	}
}

// handleMeetPage is the public booking endpoint. Accepts either
// a GET (HTML page with slots) or POST (book the slot).
func (s *HTTPServer) handleMeetPage(w http.ResponseWriter, r *http.Request) {
	slug := strings.TrimPrefix(r.URL.Path, "/meet/")
	slug = strings.TrimSuffix(slug, "/")
	e := findEventType(slug)
	if e == nil {
		http.NotFound(w, r)
		return
	}
	if r.Method == http.MethodPost {
		s.handleBookSlot(w, r, e)
		return
	}
	slots := computeSlots(e, time.Now())
	if strings.Contains(r.Header.Get("Accept"), "application/json") {
		jsonReply(w, http.StatusOK, map[string]interface{}{
			"ok":        true,
			"eventType": e,
			"slots":     slots,
		})
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	fmt.Fprint(w, renderMeetPage(e, slots))
}

func renderMeetPage(e *EventType, slots []time.Time) string {
	var opts strings.Builder
	for _, t := range slots {
		fmt.Fprintf(&opts, `<option value="%s">%s</option>`, t.Format(time.RFC3339), t.Format("Mon Jan 2 15:04"))
	}
	return fmt.Sprintf(`<!doctype html><html><head><meta charset="utf-8"><title>Book %s</title>
<style>body{font-family:system-ui;max-width:420px;margin:48px auto;padding:24px}h1{margin-top:0}input,select,button{width:100%%;padding:12px;margin:8px 0;border:1px solid #ddd;border-radius:8px;font-size:15px}button{background:#4F46E5;color:#fff;font-weight:700;border:0}</style>
</head><body>
<h1>%s</h1>
<p>%d minutes — %s</p>
<form method="POST">
  <input name="name" placeholder="Name" required>
  <input name="email" type="email" placeholder="Email" required>
  <select name="slot" required>%s</select>
  <button type="submit">Book</button>
</form>
</body></html>`, e.Title, e.Title, e.DurationMin, e.Description, opts.String())
}

func (s *HTTPServer) handleBookSlot(w http.ResponseWriter, r *http.Request, e *EventType) {
	if err := r.ParseForm(); err != nil {
		jsonError(w, http.StatusBadRequest, err.Error())
		return
	}
	name := r.PostForm.Get("name")
	email := strings.ToLower(strings.TrimSpace(r.PostForm.Get("email")))
	slotStr := r.PostForm.Get("slot")
	if name == "" || email == "" || slotStr == "" {
		http.Error(w, "missing fields", http.StatusBadRequest)
		return
	}
	starts, err := time.Parse(time.RFC3339, slotStr)
	if err != nil {
		http.Error(w, "invalid slot", http.StatusBadRequest)
		return
	}
	booking := Booking{
		ID:        randomFormID(),
		EventSlug: e.Slug,
		Name:      name,
		Email:     email,
		StartsAt:  starts,
		EndsAt:    starts.Add(time.Duration(e.DurationMin) * time.Minute),
		CreatedAt: time.Now().UTC(),
		Provider:  e.Provider,
	}

	cfg, _ := LoadConfig()
	if cfg == nil || cfg.Email == nil {
		http.Error(w, "email not configured", http.StatusPreconditionFailed)
		return
	}

	// Create the calendar event.
	var evErr error
	switch e.Provider {
	case "google":
		booking.CalEventID, booking.JoinURL, evErr = createGoogleEvent(cfg.Email, e, &booking)
	case "o365":
		booking.CalEventID, booking.JoinURL, evErr = createGraphEvent(cfg.Email, e, &booking)
	}
	if evErr != nil {
		http.Error(w, "calendar create failed: "+evErr.Error(), http.StatusBadGateway)
		return
	}

	current := loadBookings()
	meetMu.Lock()
	bookings = append(current, booking)
	_ = saveBookings()
	meetMu.Unlock()

	// Notify both sides via SMTP (best-effort).
	go func() {
		body := fmt.Sprintf("You're booked for %s with %s at %s.\n\n", e.Title, name, starts.Format(time.RFC1123))
		if booking.JoinURL != "" {
			body += "Join: " + booking.JoinURL + "\n"
		}
		_, _ = SendTransactionalEmail(SendEmailRequest{
			To:      []string{email},
			Subject: fmt.Sprintf("Confirmed: %s", e.Title),
			Body:    body,
		})
		if cfg.Email.SenderEmail != "" {
			_, _ = SendTransactionalEmail(SendEmailRequest{
				To:      []string{cfg.Email.SenderEmail},
				Subject: fmt.Sprintf("New booking: %s", e.Title),
				Body:    fmt.Sprintf("%s <%s> booked %s for %s", name, email, e.Title, starts.Format(time.RFC1123)),
			})
		}
	}()

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	fmt.Fprintf(w, `<!doctype html><html><body style='font-family:system-ui;max-width:420px;margin:48px auto;padding:24px;text-align:center'><h1>Booked!</h1><p>Check your email for the calendar invite.</p>%s</body></html>`,
		func() string {
			if booking.JoinURL != "" {
				return fmt.Sprintf(`<p><a href="%s">Join link</a></p>`, booking.JoinURL)
			}
			return ""
		}())
}

func (s *HTTPServer) handleBookings(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		jsonError(w, http.StatusMethodNotAllowed, "use GET")
		return
	}
	jsonReply(w, http.StatusOK, map[string]interface{}{"ok": true, "bookings": loadBookings()})
}
