package main

import (
	"os"
	"testing"
)

// TestSandboxBrowserBundleLifecycle proves the deploy→serverless→remove loop for
// a bundle produced by the WEB BROWSER sandbox (web/lib/sandbox/bundle.ts), not
// the Go exporter. It feeds the real exported .yaver.tgz through the agent's
// actual ImportPhoneProject (the same code path /phone/projects/receive runs)
// and then DeletePhoneProject — confirming a browser-built project deploys into
// and removes cleanly from a real Yaver Serverless target, with no server, no
// auth, and no Hetzner. The bundle is generated by e2e/sandbox-deep-test.cjs.
func TestSandboxBrowserBundleLifecycle(t *testing.T) {
	const bundlePath = "/tmp/sbx-export.tgz"
	data, err := os.ReadFile(bundlePath)
	if err != nil {
		t.Skipf("no browser bundle at %s (run e2e/sandbox-deep-test.cjs first): %v", bundlePath, err)
	}

	// Isolate to a throwaway HOME so we never touch the real ~/.yaver.
	t.Setenv("HOME", t.TempDir())

	// ── Deploy (import) — what /phone/projects/receive does ────────────────
	p, err := ImportPhoneProject(data, PhoneImportOptions{OnConflict: "overwrite"})
	if err != nil {
		t.Fatalf("ImportPhoneProject (deploy) failed: %v", err)
	}
	if p.Slug == "" {
		t.Fatal("deployed project has empty slug")
	}
	t.Logf("deployed slug=%q name=%q", p.Slug, p.Name)

	// Schema must have materialized into real tables.
	if p.Stats == nil {
		t.Fatal("deployed project has no stats")
	}
	if got := p.Stats.PerTable["todos"]; got < 4 {
		t.Fatalf("expected >=4 live todos rows in deployed bundle, got %d (stats=%+v)", got, p.Stats)
	}
	if p.Stats.PerTable["users"] < 1 {
		t.Fatalf("expected seeded users, got %d", p.Stats.PerTable["users"])
	}
	t.Logf("serverless data present: todos=%d users=%d", p.Stats.PerTable["todos"], p.Stats.PerTable["users"])

	// Reload to prove it's persisted on the target, then read it back.
	reloaded, err := LoadPhoneProject(p.Slug)
	if err != nil {
		t.Fatalf("LoadPhoneProject after deploy failed: %v", err)
	}
	if reloaded.Stats.PerTable["todos"] < 4 {
		t.Fatalf("reload lost rows: %+v", reloaded.Stats)
	}

	// ── Remove (delete) ────────────────────────────────────────────────────
	if err := DeletePhoneProject(p.Slug); err != nil {
		t.Fatalf("DeletePhoneProject (remove) failed: %v", err)
	}
	exists, err := phoneProjectExists(p.Slug)
	if err != nil {
		t.Fatalf("phoneProjectExists after remove errored: %v", err)
	}
	if exists {
		t.Fatal("project still exists after remove")
	}
	if _, err := LoadPhoneProject(p.Slug); err == nil {
		t.Fatal("LoadPhoneProject succeeded after remove — should be gone")
	}
	t.Logf("removed cleanly: %s", p.Slug)
}
