package main

// shots_analyzer.go — Part E: derive a screenshot nav plan from an
// expo-router project and emit a Maestro flow that walks it.
//
// This is deliberately heuristic. Apps like sfmg are i18n with zero
// testIDs, so a fully blind generated flow is fragile — the *committed
// override* (.yaver/shots.flow.yaml) is the reliable path. The analyzer's
// job is to (a) find that override if present, and (b) otherwise write a
// runnable first-draft flow the user can edit + commit.

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// ScreenNode is one screenshot-worthy screen discovered in the route tree.
type ScreenNode struct {
	Route  string
	File   string
	IsTab  bool
	Hidden bool
}

// ShotsAnalysis is the result of inspecting an expo-router project.
type ShotsAnalysis struct {
	BundleID      string
	Screens       []ScreenNode
	VisibleTabs   int
	HasLangSelect bool
	HasAuthGate   bool
}

// findShotsFlow returns a committed Maestro flow path if the project ships
// one, else "". Mirrors findExistingExerciseFlow's convention.
func findShotsFlow(appDir string) string {
	candidates := []string{
		filepath.Join(appDir, ".yaver", "shots.flow.yaml"),
		filepath.Join(appDir, "e2e", "shots.flow.yaml"),
		filepath.Join(appDir, "maestro", "shots.yaml"),
	}
	for _, p := range candidates {
		if st, err := os.Stat(p); err == nil && !st.IsDir() {
			return p
		}
	}
	return ""
}

// readBundleIDFromAppJSON pulls expo.ios.bundleIdentifier from app.json /
// app.config.json. Returns "" if not found.
func readBundleIDFromAppJSON(appDir string) string {
	for _, name := range []string{"app.json", "app.config.json"} {
		data, err := os.ReadFile(filepath.Join(appDir, name))
		if err != nil {
			continue
		}
		var parsed struct {
			Expo struct {
				IOS struct {
					BundleIdentifier string `json:"bundleIdentifier"`
				} `json:"ios"`
			} `json:"expo"`
		}
		if json.Unmarshal(data, &parsed) == nil && parsed.Expo.IOS.BundleIdentifier != "" {
			return parsed.Expo.IOS.BundleIdentifier
		}
	}
	return ""
}

// expoAppDir returns the expo-router app/ directory: src/app or app.
func expoAppDir(appDir string) string {
	for _, rel := range []string{filepath.Join("src", "app"), "app"} {
		p := filepath.Join(appDir, rel)
		if st, err := os.Stat(p); err == nil && st.IsDir() {
			return p
		}
	}
	return ""
}

var tabsScreenRe = regexp.MustCompile(`<Tabs\.Screen\s+name=["'` + "`" + `]([^"'` + "`" + `]+)["'` + "`" + `]`)

// AnalyzeExpoRouter inspects the project and returns a structured summary.
func AnalyzeExpoRouter(appDir string) (*ShotsAnalysis, error) {
	a := &ShotsAnalysis{BundleID: readBundleIDFromAppJSON(appDir)}
	routerDir := expoAppDir(appDir)
	if routerDir == "" {
		return nil, fmt.Errorf("no expo-router app/ dir found under %s (looked at src/app and app)", appDir)
	}

	if _, err := os.Stat(filepath.Join(routerDir, "language-select.tsx")); err == nil {
		a.HasLangSelect = true
	}
	if _, err := os.Stat(filepath.Join(routerDir, "auth")); err == nil {
		a.HasAuthGate = true
	}
	if _, err := os.Stat(filepath.Join(routerDir, "agent-setup.tsx")); err == nil {
		a.HasAuthGate = true // sfmg gates via agent-setup, not auth/welcome
	}

	// Tabs.
	layout := filepath.Join(routerDir, "(tabs)", "_layout.tsx")
	if data, err := os.ReadFile(layout); err == nil {
		src := string(data)
		locs := tabsScreenRe.FindAllStringSubmatchIndex(src, -1)
		for i, loc := range locs {
			// loc: [matchStart, matchEnd, group1Start, group1End].
			name := src[loc[2]:loc[3]]
			// Bound this tag to the start of the next Tabs.Screen match (or
			// EOF) so an href:null on a *later* tab can't bleed in.
			tagEnd := len(src)
			if i+1 < len(locs) {
				tagEnd = locs[i+1][0]
			}
			node := ScreenNode{Route: name, File: name + ".tsx", IsTab: true}
			node.Hidden = hrefNullInTag(src[loc[0]:tagEnd])
			if !node.Hidden {
				a.VisibleTabs++
			}
			a.Screens = append(a.Screens, node)
		}
	}
	return a, nil
}

// hrefNullInTag reports whether a single Tabs.Screen tag declares href:null.
func hrefNullInTag(tag string) bool {
	return strings.Contains(strings.ReplaceAll(tag, " ", ""), "href:null")
}

// generateShotsFlow writes a runnable first-draft Maestro flow for the
// project and returns its path. The flow is best-effort (advance-buttons +
// position-tapped tabs) and is written as `.generated` so it never
// clobbers a committed override. Designed to be copied to
// .yaver/shots.flow.yaml and edited.
func generateShotsFlow(appDir, bundleID string, a *ShotsAnalysis) (string, error) {
	dir := filepath.Join(appDir, ".yaver")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, "shots.flow.yaml.generated")

	tabs := a.VisibleTabs
	if tabs <= 0 {
		tabs = 1
	}

	var b strings.Builder
	b.WriteString("# Generated by `yaver shots`. This is a best-effort first draft.\n")
	b.WriteString("# Copy to `.yaver/shots.flow.yaml` and edit for your app, then commit.\n")
	b.WriteString("# Apps with i18n labels / no testIDs need hand-tuning here.\n")
	fmt.Fprintf(&b, "appId: %s\n", bundleID)
	b.WriteString("---\n")
	b.WriteString("- launchApp:\n")
	b.WriteString("    clearState: true   # force first-run onboarding so the walk is deterministic\n")
	b.WriteString("- waitForAnimationToEnd\n")

	if a.HasLangSelect {
		b.WriteString("\n# Language gate — tap the first option (edit to your locale's label).\n")
		b.WriteString("- tapOn:\n")
		b.WriteString("    point: \"50%,40%\"\n")
		b.WriteString("- waitForAnimationToEnd\n")
	}

	if a.HasAuthGate {
		b.WriteString("\n# Onboarding / guest gate — advance through the setup steps.\n")
		b.WriteString("# These tap common 'next'/'skip' button labels; add your app's\n")
		b.WriteString("# exact i18n strings. Wrapped in optional blocks so a missing\n")
		b.WriteString("# label doesn't abort the flow.\n")
		for _, label := range []string{"Next", "Continue", "İleri", "Forward", "Skip", "Şimdilik geç", "Start", "Başla"} {
			fmt.Fprintf(&b, "- runFlow:\n    when:\n      visible: \"%s\"\n    commands:\n      - tapOn: \"%s\"\n      - waitForAnimationToEnd\n", label, label)
		}
	}

	b.WriteString("\n# Fast-forward any intro animation by tapping center a few times.\n")
	for i := 0; i < 3; i++ {
		b.WriteString("- tapOn:\n    point: \"50%,50%\"\n- waitForAnimationToEnd\n")
	}

	b.WriteString("\n# Capture each visible bottom-tab by position (locale-proof).\n")
	for i := 0; i < tabs; i++ {
		x := int(float64(i)*100.0/float64(tabs) + 50.0/float64(tabs))
		label := "screen"
		// Prefer a real route name if we have one for this index.
		visIdx := 0
		for _, s := range a.Screens {
			if s.IsTab && !s.Hidden {
				if visIdx == i {
					label = s.Route
					break
				}
				visIdx++
			}
		}
		fmt.Fprintf(&b, "- tapOn:\n    point: \"%d%%,96%%\"\n- waitForAnimationToEnd\n- takeScreenshot: %02d_%s\n", x, i+1, label)
	}

	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return "", err
	}
	return path, nil
}
