package main

// vibe_preview_exercise.go — Phase 7: drive the running app with
// Maestro flows while a clip records. Without this, clip videos are
// 12 s of staring at the home screen. With it, the recording captures
// a real interaction — exactly the demo a vibe-coder wants to see.
//
// Strategy (best-effort, never blocks the clip):
//   1. If `<workDir>/e2e/<project>.flow.yaml` exists, run that.
//   2. Otherwise, write a tiny canned YAML to ~/.yaver/vibe-preview/
//      exercises/<project>/<clipID>.yaml that scrolls + taps blindly.
//      Saved exercises become reusable seeds for future runs and for
//      a manual `maestro test` from the dev's own terminal.
//   3. If `maestro` isn't on PATH, this whole module is a no-op — the
//      recorder still produces a clip, just an idle one.
//
// All work runs in a goroutine so it can't slow down the recorder
// startup. Failure is logged but never surfaced as an error.

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// vibeExerciseDir is the on-disk root for generated + replayable
// exercises. One subdir per project; one .yaml per clip.
func (m *VibePreviewManager) vibeExerciseDir(project string) string {
	return filepath.Join(m.resolveDiskRoot(), "exercises", sanitizeBranchName(project))
}

// findExistingExerciseFlow returns the absolute path to a project-
// authored Maestro flow if one exists, else "". Looks in workDir for
// the conventional `e2e/<project>.flow.yaml` first, then for any
// generic `e2e/smoke.flow.yaml`.
func findExistingExerciseFlow(workDir, project string) string {
	if workDir == "" {
		return ""
	}
	candidates := []string{
		filepath.Join(workDir, "e2e", project+".flow.yaml"),
		filepath.Join(workDir, "e2e", "smoke.flow.yaml"),
		filepath.Join(workDir, "maestro", project+".yaml"),
	}
	for _, p := range candidates {
		if st, err := os.Stat(p); err == nil && !st.IsDir() {
			return p
		}
	}
	return ""
}

// writeCannedExerciseFlow drops a generic scroll+tap flow at the path
// and returns it. Idempotent — overwrites silently. The canned flow is
// platform-agnostic Maestro YAML; it works against any iOS sim or
// Android emulator without knowing what app is running.
func writeCannedExerciseFlow(path, hint string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	yaml := strings.Builder{}
	yaml.WriteString("# Auto-generated by yaver vibe-preview exercise driver.\n")
	yaml.WriteString("# Drives the running app for ~10 s while the clip recorder captures.\n")
	if hint != "" {
		yaml.WriteString("# Kick context: ")
		yaml.WriteString(strings.ReplaceAll(hint, "\n", " "))
		yaml.WriteString("\n")
	}
	yaml.WriteString("appId: \"*\"\n") // wildcard — Maestro picks the foregrounded app
	yaml.WriteString("---\n")
	yaml.WriteString("- launchApp\n")
	yaml.WriteString("- waitForAnimationToEnd\n")
	yaml.WriteString("- takeScreenshot: yaver-vibe-1\n")
	yaml.WriteString("- swipe:\n")
	yaml.WriteString("    direction: UP\n")
	yaml.WriteString("- waitForAnimationToEnd\n")
	yaml.WriteString("- takeScreenshot: yaver-vibe-2\n")
	yaml.WriteString("- swipe:\n")
	yaml.WriteString("    direction: DOWN\n")
	yaml.WriteString("- waitForAnimationToEnd\n")
	yaml.WriteString("- tapOn:\n")
	yaml.WriteString("    point: \"50%,50%\"\n")
	yaml.WriteString("- waitForAnimationToEnd\n")
	yaml.WriteString("- takeScreenshot: yaver-vibe-3\n")
	return os.WriteFile(path, []byte(yaml.String()), 0o600)
}

// MaestroAvailable reports whether the maestro binary is on PATH.
// Cached on first call — exec.LookPath is cheap but the result doesn't
// change inside an agent process.
var maestroPath = func() string {
	p, _ := exec.LookPath("maestro")
	return p
}()

// MaestroAvailable is exported for the doctor + sandbox preflight.
func MaestroAvailable() bool { return maestroPath != "" }

// ExerciseClip is the entrypoint called by StartClip when the source is
// a simulator/emulator. workDir is the LoopState's workDir (or empty if
// invoked from outside autodev — the canned flow still works without
// it). hint is short free text from the caller (kick prompt summary).
//
// Returns immediately; the actual work runs in a goroutine. The clip
// recorder context is what gates the lifetime — when the recorder
// stops, the goroutine's context cancellation kills any in-flight
// `maestro test` subprocess.
func (m *VibePreviewManager) ExerciseClip(ctx context.Context, clipID, project, workDir, hint string) {
	if m == nil || !MaestroAvailable() {
		return
	}
	go func() {
		flow := findExistingExerciseFlow(workDir, project)
		generated := false
		if flow == "" {
			generated = true
			flow = filepath.Join(m.vibeExerciseDir(project), clipID+".yaml")
			if err := writeCannedExerciseFlow(flow, hint); err != nil {
				log.Printf("[vibe-exercise] write canned flow %s: %v", flow, err)
				return
			}
		}
		cmd := exec.CommandContext(ctx, maestroPath, "test", flow)
		// Maestro is verbose; redirect to stderr so it lands in the
		// agent log without polluting the clip-recorder's output.
		cmd.Stdout = os.Stderr
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			// Most likely cause: no booted simulator, or the canned flow
			// hit an unexpected screen. Either way the clip still
			// captures whatever was visible. Log + move on.
			log.Printf("[vibe-exercise] %s (flow=%s, generated=%v): %v",
				project, flow, generated, err)
		}
	}()
}

// SeedExerciseFromContext writes a canned flow for a project even when
// no clip is recording, so the dev can build up a library by repeatedly
// running yaver. Used by the future Phase 7.1 "seed exercises from
// previous successful runs" workflow. Returns the on-disk path.
func (m *VibePreviewManager) SeedExerciseFromContext(project, name, hint string) (string, error) {
	if project == "" {
		return "", fmt.Errorf("project required")
	}
	if name == "" {
		name = "seed"
	}
	dir := m.vibeExerciseDir(project)
	path := filepath.Join(dir, name+".yaml")
	if err := writeCannedExerciseFlow(path, hint); err != nil {
		return "", err
	}
	return path, nil
}
