set-option -gw xterm-keys on

bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
unbind '"'
unbind %

bind-key Up select-pane -U
bind-key Down select-pane -D
bind-key Left select-pane -L
bind-key Right select-pane -R

set -g history-limit 1000000

set -g status-bg "#262626"
set -g status-fg white
set -g status-right ""

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

setw -g mode-keys vi

run '~/.tmux/plugins/tpm/tpm'
