package testkit

import (
	"context"
	"fmt"
	"strings"
	"time"
)

// Autonomous fix loop hook.
//
// The agent already runs an autonomous-develop loop in another
// goroutine that drives the user's chosen AI to make code changes.
// This file is the seam between that loop and yaver-test-sdk: when a
// spec fails, the runner can hand the failure back to the loop, the
// loop proposes a patch (a code edit, a selector update, a snapshot
// rebase), the runner re-runs the same single spec, and the loop
// commits when it goes green. The dev approves the final commit from
// the mobile app.
//
// What this file owns:
//
//   - The shape of an "autonomous fix request" so the rest of the
//     codebase can produce one without depending on the AI loop.
//   - A small dispatch table that the autonomous loop can register
//     callbacks against.
//   - A bounded retry loop so we never spin forever on a flaky LLM.
//
// What this file does NOT own:
//
//   - The actual model call. That's the autonomous loop's job; this
//     file only routes the request and parses the response.

// FixRequest is the structured "please fix this" message handed to
// the autonomous loop. Generated by the runner immediately after a
// failed run.
type FixRequest struct {
	Spec      *Spec
	StepIndex int
	Phase     string
	Action    string // human label of the failing step
	Error     string
	Screenshot string
	// DOMHTML is the captured page HTML at failure time. Optional —
	// only set when the runner managed to read the DOM before the
	// page tore down.
	DOMHTML string
	// History is the most recent runs of this spec, oldest first.
	// Lets the loop notice "this has been failing for 10 runs in a
	// row" and reach for a different strategy.
	History []HistorySpecResult
}

// FixResult is what the autonomous loop returns. Either a patch the
// runner can apply directly (a new selector for a single step) or a
// "the loop committed a code change, please re-run" signal.
type FixResult struct {
	// Strategy is one of "selector_replace", "code_edit",
	// "snapshot_rebase", "give_up".
	Strategy string

	// SelectorReplace is set when Strategy == "selector_replace".
	// The runner patches the failing step's selector in-memory and
	// retries without needing to reload the YAML from disk.
	SelectorReplace string

	// Notes is human-readable, surfaced in the mobile UI's "fixes"
	// drawer so the dev sees what the loop tried.
	Notes string

	// Confidence is 0..1. The runner uses this to decide whether
	// to apply the fix automatically or queue it for the dev's
	// approval.
	Confidence float64
}

// FixHandler is the function the autonomous loop registers. The
// runner calls it; the loop is responsible for the LLM round trip.
type FixHandler func(ctx context.Context, req FixRequest) (*FixResult, error)

// fixDispatch is the global registry. There's at most one handler
// installed at a time — the autonomous loop replaces it on its
// startup.
var fixDispatch FixHandler

// RegisterFixHandler installs the autonomous loop's handler. Pass
// nil to detach.
func RegisterFixHandler(h FixHandler) {
	fixDispatch = h
}

// AttemptAutonomousFix is the runner's "we just failed, see if the
// loop can salvage this" call. Returns the FixResult or nil if no
// handler is registered or the loop gave up.
func AttemptAutonomousFix(ctx context.Context, req FixRequest) *FixResult {
	if fixDispatch == nil {
		return nil
	}
	cctx, cancel := context.WithTimeout(ctx, 60*time.Second)
	defer cancel()
	res, err := fixDispatch(cctx, req)
	if err != nil {
		return &FixResult{
			Strategy: "give_up",
			Notes:    fmt.Sprintf("autonomous fix handler: %v", err),
		}
	}
	return res
}

// SelectorReplaceFromSelfHeal is the bridge from the LLM-driven
// SelfHealSelector primitive to a FixResult shape. Used by the
// default autonomous loop implementation when the failure is a
// "selector not found" error.
func SelectorReplaceFromSelfHeal(ctx context.Context, failedSelector, dom, intent string) *FixResult {
	if dom == "" {
		return nil
	}
	r, err := SelfHealSelector(ctx, SelfHealRequest{
		FailedSelector: failedSelector,
		DOMHTML:        dom,
		Intent:         intent,
	})
	if err != nil {
		return &FixResult{
			Strategy: "give_up",
			Notes:    err.Error(),
		}
	}
	return &FixResult{
		Strategy:        "selector_replace",
		SelectorReplace: r.Selector,
		Notes:           r.Reasoning,
		Confidence:      0.65,
	}
}

// IsSelectorFailure is a heuristic check on a step error message —
// returns true when the failure looks like "the selector didn't
// match anything," in which case the runner should call into the
// autonomous loop with a self-heal request rather than escalating.
func IsSelectorFailure(err error) bool {
	if err == nil {
		return false
	}
	msg := err.Error()
	for _, marker := range []string{
		"could not find node",
		"no such element",
		"not visible",
		"context deadline exceeded",
	} {
		if strings.Contains(msg, marker) {
			return true
		}
	}
	return false
}
