#!/usr/bin/env node
// vendor-xterm.mjs — bundle xterm.js + addon-fit + css into a single TS
// string module so the in-app WebView terminal (XtermView.tsx) renders a
// true VT grid OFFLINE (no CDN — the Beam Pro / glasses use case is on a
// beach with no signal). Run after bumping the @xterm devDeps:
//
//   cd mobile && npm i -D @xterm/xterm @xterm/addon-fit
//   node ../scripts/vendor-xterm.mjs
//
// The source is JSON.stringify'd (not backtick-wrapped) so backticks/${}
// inside xterm's minified source can't break the template. The generated
// file is committed — it IS what ships; node_modules is not on the device.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const mobile = join(here, "..", "mobile");
const nm = join(mobile, "node_modules");

const read = (p) => readFileSync(join(nm, p), "utf8");

const xtermJs = read("@xterm/xterm/lib/xterm.js");
const xtermCss = read("@xterm/xterm/css/xterm.css");
const fitJs = read("@xterm/addon-fit/lib/addon-fit.js");

const out = join(mobile, "src", "components", "vendor", "xtermBundle.ts");
mkdirSync(dirname(out), { recursive: true });

const header = `// AUTO-GENERATED by scripts/vendor-xterm.mjs — DO NOT EDIT BY HAND.
// xterm.js (${(xtermJs.length / 1024) | 0}KB) + addon-fit + css, inlined for the
// offline in-app WebView terminal. Regenerate after bumping @xterm devDeps:
//   cd mobile && node ../scripts/vendor-xterm.mjs
/* eslint-disable */
`;

const body =
  header +
  `export const XTERM_JS = ${JSON.stringify(xtermJs)};\n` +
  `export const XTERM_FIT_JS = ${JSON.stringify(fitJs)};\n` +
  `export const XTERM_CSS = ${JSON.stringify(xtermCss)};\n`;

writeFileSync(out, body);
console.log(`wrote ${out} (${(body.length / 1024) | 0}KB)`);
