// macSetupAirDrop — "Set up my Mac" cold-start accelerant.
//
// A brand-new Mac has nothing running, so the usual fast transports
// (LAN beacon UDP 19837, BLE, phone-shown QR) are all useless for the
// INSTALL step — they every one presuppose the agent is already up.
// The only OS-level channel that can reach a cold Mac with nothing
// pre-installed is AirDrop (Universal Clipboard is the fallback).
//
// So we generate a double-clickable `yaver-setup.command` and hand it
// to the share sheet. The user AirDrops it to their Mac, double-clicks
// (one Gatekeeper "Open?" click), and the script:
//   1. installs the CLI:           npm install -g yaver-cli
//   2. starts the agent unauthed:  yaver serve
// An unauthed agent comes up in bootstrap-beacon mode automatically
// (desktop/agent/beacon.go:127 — `needsAuth := userID == ""`), so the
// phone's already-running beacon listener discovers it and adopts it
// by pushing the signed-in token to /auth/pair/submit
// (mobile/src/lib/pairDevice.ts::adoptBootstrapDevice). Net user
// typing on the Mac: zero.
//
// No agent changes: this only orchestrates EXISTING cold-start
// behaviour. If npm is missing the script deep-links the Node
// installer and stops with a clear message rather than dead-ending.

import * as Sharing from "expo-sharing";
// expo-file-system ~19 (SDK 54) moved the classic write/cacheDirectory
// API behind /legacy. Import it explicitly so we don't depend on the
// new File/Directory class API that the rest of the app hasn't moved to.
import * as FileSystem from "expo-file-system/legacy";

/** The one-liner we also surface as copy-to-clipboard text. Kept in
 *  one place so the AirDrop script and the copyable command never
 *  drift. `yaver serve` (not `yaver auth`) is deliberate: serve while
 *  unauthed → bootstrap beacon → silent phone adopt, no Mac sign-in. */
export const MAC_SETUP_ONELINER = "npm install -g yaver-cli && yaver serve";

/** Body of the double-clickable macOS script. Pure function so it can
 *  be unit-tested without touching the filesystem. */
export function buildMacSetupScript(): string {
  // .command files run under /bin/bash by Terminal on double-click.
  // We keep this dependency-free and defensive: a fresh Mac may lack
  // Node entirely, in which case `npm` won't exist and the install
  // would fail with a cryptic error. Detect that up front and send
  // the user to the official installer instead.
  return [
    "#!/bin/bash",
    "# yaver-setup.command — double-click to install Yaver + pair this Mac to your phone.",
    "# Generated by the Yaver mobile app. Safe to delete after setup.",
    "set -e",
    "",
    'echo ""',
    'echo "  Yaver — setting up this Mac…"',
    'echo ""',
    "",
    "# 1. Node/npm are required to install the CLI. A bare Mac may not",
    "#    have them — fail loud and open the official installer rather",
    "#    than dying on a cryptic 'npm: command not found'.",
    'if ! command -v npm >/dev/null 2>&1; then',
    '  echo "  Node.js is required and was not found."',
    '  echo "  Opening the Node.js installer — install it, then double-click this file again."',
    '  open "https://nodejs.org/en/download/prebuilt-installer" || true',
    "  exit 1",
    "fi",
    "",
    "# 2. Install (or update) the single supported distribution.",
    'echo "  Installing yaver-cli (this can take a minute)…"',
    "npm install -g yaver-cli",
    "",
    "# 3. Start the agent. With no auth on disk it comes up in",
    "#    bootstrap-beacon mode and announces itself on the LAN; your",
    "#    phone (already signed in) sees it and pairs automatically —",
    "#    no sign-in needed here. Keep this window open.",
    'echo ""',
    'echo "  Starting Yaver. Keep your phone nearby — it will pair this Mac automatically."',
    'echo "  (You can close this window once your phone shows the Mac as connected.)"',
    'echo ""',
    "yaver serve",
    "",
  ].join("\n");
}

export interface MacSetupShareResult {
  ok: boolean;
  /** True when the device can't share at all (no AirDrop / share sheet
   *  available, e.g. simulator). Caller should fall back to the
   *  copy-command path. */
  unsupported?: boolean;
  error?: string;
}

/**
 * Write the setup script to a temp file and open the iOS share sheet
 * (AirDrop is the top row when a nearby Mac is signed into the same
 * Apple ID). Returns {unsupported:true} when sharing isn't available
 * so the caller can fall back to copy-to-clipboard.
 */
export async function shareMacSetupScript(): Promise<MacSetupShareResult> {
  try {
    if (!(await Sharing.isAvailableAsync())) {
      return { ok: false, unsupported: true };
    }
    const dir = FileSystem.cacheDirectory;
    if (!dir) {
      return { ok: false, unsupported: true };
    }
    const fileUri = dir + "yaver-setup.command";
    // Default encoding is UTF-8; expo-file-system@19's /legacy export
    // doesn't re-export EncodingType, and the script is plain ASCII.
    await FileSystem.writeAsStringAsync(fileUri, buildMacSetupScript());
    await Sharing.shareAsync(fileUri, {
      // public.shell-script so macOS recognises it as runnable; the
      // dialogTitle shows on the iOS sheet.
      UTI: "public.shell-script",
      mimeType: "text/x-shellscript",
      dialogTitle: "AirDrop to your Mac, then double-click it",
    });
    return { ok: true };
  } catch (err: any) {
    return { ok: false, error: err?.message || "Couldn't open the share sheet." };
  }
}
